# Generated by Selenium IDE

import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support import expected_conditions as EC
import logging


def add_akt(q):
    logger = logging.getLogger(__name__)

    logger.debug(f' Заявление {q.setup["request_id"]} подписываем акт')
    user_data_dir = "/home/nuanred/.config/google-chrome/'test'"
    chrome_options = Options()
    chrome_options.add_argument(f"user-data-dir={user_data_dir}")

    chrome_options.add_argument("--start-maximized")
    driver = webdriver.Chrome(options=chrome_options)
    # ----------------------------- Переходим на нужнаую страницу ------------------------
    driver.get("https://lk-test.egais.ru/dev/")
    driver.refresh()

    driver.find_element(By.ID, "mat-input-0").send_keys("wageworker")
    driver.find_element(By.ID, "mat-input-1").send_keys("GetMeT0kenPlease-246")
    driver.find_element(
        By.XPATH, "//mat-form-field[contains(@class,'mat-form-field ng-tns-c58-1')]/following-sibling::button[1]").click()
    time.sleep(2)
    # ----------------------------- Переходим на нужную страницу ------------------------
    driver.get(
        f"https://lk-test.egais.ru/cabinet/licenses/inProcess/{q.setup['request_id']}")
    # 2 | setWindowSize | 1854x1048 |

    time.sleep(5)
    # 3 | click | css=#mat-tab-label-0-2 > .mat-tab-label-content |
    driver.find_element(
        By.CSS_SELECTOR, "#mat-tab-label-0-2 > .mat-tab-label-content").click()
    # 4 | click | css=.ng-tns-c58-66 > .mat-form-field-infix |
    driver.find_element(
        By.CSS_SELECTOR, ".ng-tns-c58-66 > .mat-form-field-infix").click()
    # 5 | click | css=.mat-option-text |
    driver.find_element(By.CSS_SELECTOR, ".mat-option-text").click()
    # 6 | click | css=.cdk-overlay-backdrop |
    driver.find_element(By.CSS_SELECTOR, ".cdk-overlay-backdrop").click()
    # 7 | click | css=.mat-focused |
    driver.find_element(By.CSS_SELECTOR, ".mat-focused").click()
    # 8 | click | id=mat-input-4 |
    driver.find_element(By.ID, "mat-input-4").click()
    # 9 | click | id=mat-input-6 |
    driver.find_element(By.ID, "mat-input-6").click()
    # 10 | mouseDownAt | css=.statement | 16.00390625,919.3359375
    element = driver.find_element(By.CSS_SELECTOR, ".statement")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 11 | mouseMoveAt | css=.statement | 16.00390625,919.3359375
    element = driver.find_element(By.CSS_SELECTOR, ".statement")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 12 | mouseUpAt | css=.statement | 16.00390625,919.3359375
    element = driver.find_element(By.CSS_SELECTOR, ".statement")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 13 | click | css=.statement |
    driver.find_element(By.CSS_SELECTOR, ".statement").click()
    # 14 | click | id=mat-input-7 |
    driver.find_element(By.ID, "mat-input-7").click()
    # 15 | type | id=mat-input-7 | 2025-01-23
    driver.find_element(By.ID, "mat-input-7").send_keys("2025-01-23")
    # 16 | click | id=mat-input-8 |
    driver.find_element(By.ID, "mat-input-8").click()
    # 17 | type | id=mat-input-8 | 16:30
    driver.find_element(By.ID, "mat-input-8").send_keys("16:30")
    # 18 | click | id=mat-input-9 |
    driver.find_element(By.ID, "mat-input-9").click()
    # 19 | doubleClick | id=mat-input-9 |
    element = driver.find_element(By.ID, "mat-input-9")
    actions = ActionChains(driver)
    actions.double_click(element).perform()
    # 20 | type | id=mat-input-9 | 16:30
    driver.find_element(By.ID, "mat-input-9").send_keys("16:30")
    # 21 | click | css=.ng-tns-c58-75 > .mat-form-field-infix |
    driver.find_element(
        By.CSS_SELECTOR, ".ng-tns-c58-75 > .mat-form-field-infix").click()
    # 22 | click | css=.flex-column > .ng-star-inserted |
    driver.find_element(
        By.CSS_SELECTOR, ".flex-column > .ng-star-inserted").click()
    # 23 | click | id=mat-input-11 |
    driver.find_element(By.ID, "mat-input-11").click()
    # 24 | click | css=.statement |
    driver.find_element(By.CSS_SELECTOR, ".statement").click()
    # 25 | click | css=.mat-focused |
    driver.find_element(By.CSS_SELECTOR, ".mat-focused").click()
    # 26 | mouseDownAt | css=.flex-column > .ng-star-inserted | 4.00390625,977.4453125
    element = driver.find_element(
        By.CSS_SELECTOR, ".flex-column > .ng-star-inserted")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 27 | mouseMoveAt | css=.flex-column > .ng-star-inserted | 4.00390625,977.4453125
    element = driver.find_element(
        By.CSS_SELECTOR, ".flex-column > .ng-star-inserted")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 28 | mouseUpAt | css=.flex-column > .ng-star-inserted | 4.00390625,977.4453125
    element = driver.find_element(
        By.CSS_SELECTOR, ".flex-column > .ng-star-inserted")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 29 | click | css=.flex-column > .ng-star-inserted |
    driver.find_element(
        By.CSS_SELECTOR, ".flex-column > .ng-star-inserted").click()
    # 30 | click | css=.statement |
    driver.find_element(By.CSS_SELECTOR, ".statement").click()
    # 31 | click | id=mat-input-15 |
    driver.find_element(By.ID, "mat-input-15").click()
    # 32 | click | id=mat-input-16 |
    driver.find_element(By.ID, "mat-input-16").click()
    # 33 | click | id=mat-input-16 |
    driver.find_element(By.ID, "mat-input-16").click()
    # 34 | click | css=.mat-focused |
    driver.find_element(By.CSS_SELECTOR, ".mat-focused").click()
    # 35 | runScript | window.scrollTo(0,987.5) |
    driver.execute_script("window.scrollTo(0,987.5)")
    # 36 | click | css=.ng-tns-c58-83 > .mat-form-field-infix |
    driver.find_element(
        By.CSS_SELECTOR, ".ng-tns-c58-83 > .mat-form-field-infix").click()
    # 37 | click | css=.mat-focused |
    driver.find_element(By.CSS_SELECTOR, ".mat-focused").click()
    # 38 | click | id=mat-input-19 |
    driver.find_element(By.ID, "mat-input-19").click()
    # 39 | click | css=.ml-3 > .mat-button-wrapper |
    driver.find_element(By.CSS_SELECTOR, ".ml-3 > .mat-button-wrapper").click()
    # 40 | click | css=.cdk-focused |
    driver.find_element(By.CSS_SELECTOR, ".cdk-focused").click()
    # 41 | runScript | window.scrollTo(0,0) |
    driver.execute_script("window.scrollTo(0,0)")
    # 42 | click | css=.mat-expansion-panel-header-title |
    driver.find_element(
        By.CSS_SELECTOR, ".mat-expansion-panel-header-title").click()
    # 43 | click | css=.cdk-focused > .mat-button-wrapper |
    driver.find_element(
        By.CSS_SELECTOR, ".cdk-focused > .mat-button-wrapper").click()
    # 44 | runScript | window.scrollTo(0,1057.5) |
    driver.execute_script("window.scrollTo(0,1057.5)")
