# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
class TestTest22():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test22(self):
    # Test name: test22
    # Step # | name | target | value
    # 1 | open | /dev | 
    self.driver.get("https://lk-test.egais.ru/dev")
    # 2 | setWindowSize | 1854x1048 | 
    self.driver.set_window_size(1854, 1048)
    # 3 | type | id=mat-input-0 | wageworker
    self.driver.find_element(By.ID, "mat-input-0").send_keys("wageworker")
    # 4 | type | id=mat-input-1 | GetMeT0kenPlease-246
    self.driver.find_element(By.ID, "mat-input-1").send_keys("GetMeT0kenPlease-246")
    # 5 | click | id=mat-input-0 | 
    self.driver.find_element(By.ID, "mat-input-0").click()
    # 6 | click | css=.mat-card |
    time.sleep(5)
    # self.driver.find_element(By.CSS_SELECTOR, ".mat-card").click()
    # 7 | doubleClick | css=.mat-card | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-card")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 8 | click | css=.ng-tns-c58-1 > .mat-form-field-infix | 
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c58-1 > .mat-form-field-infix").click()
    # 9 | click | css=app-root > .ng-star-inserted | 
    self.driver.find_element(By.CSS_SELECTOR, "app-root > .ng-star-inserted").click()
    # 10 | click | css=.mat-raised-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".mat-raised-button").click()
    # 11 | click | css=.ng-star-inserted:nth-child(12) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(12) span").click()
    # 12 | click | css=.card-with-totals:nth-child(2) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".card-with-totals:nth-child(2) > span").click()
  
